<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/** Video Revenue Share V1: reserve-funded monthly allocations by qualified watch time. */
class Nfinite_Creators_Video_Earnings {
	const DB_VERSION='1.0.0'; const DB_OPTION='nfinite_video_earnings_db_version'; const OPTION_KEY='nfinite_video_earnings_settings'; const CRON_HOOK='nfinite_video_earnings_sync';
	public static function init(){
		add_action('init',array(__CLASS__,'maybe_install'),9); add_action('admin_menu',array(__CLASS__,'admin_menu'));
		foreach(array('save_settings','add_reserve','sync_period','finalize_period','pay_period') as $a){ add_action('admin_post_nfinite_video_'.$a,array(__CLASS__,'admin_'.$a)); }
		add_action(self::CRON_HOOK,array(__CLASS__,'cron_sync')); add_action('add_meta_boxes_nfinite_episode',array(__CLASS__,'add_monetization_box')); add_action('add_meta_boxes_nfinite_video',array(__CLASS__,'add_monetization_box')); add_action('save_post_nfinite_episode',array(__CLASS__,'save_monetization_box'),50,2); add_action('save_post_nfinite_video',array(__CLASS__,'save_monetization_box'),50,2); add_action('nfinite_video_engagement_qualified',array(__CLASS__,'qualified_changed'),10,2); add_action('wp',array(__CLASS__,'ensure_cron'));
	}
	public static function settings(){ return wp_parse_args((array)get_option(self::OPTION_KEY,array()),array('enabled'=>'0','currency'=>'USD','monthly_budget_minor'=>0,'auto_sync'=>'1')); }
	public static function enabled(){ $s=self::settings(); return '1'===(string)$s['enabled']; }
	public static function periods_table(){global $wpdb;return $wpdb->prefix.'nfinite_video_periods';} public static function allocations_table(){global $wpdb;return $wpdb->prefix.'nfinite_video_allocations';} public static function reserve_table(){global $wpdb;return $wpdb->prefix.'nfinite_video_reserve';}
	public static function maybe_install(){if(self::DB_VERSION!==(string)get_option(self::DB_OPTION,''))self::install();}
	public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();$p=self::periods_table();$a=self::allocations_table();$r=self::reserve_table();
		dbDelta("CREATE TABLE {$p} (id bigint unsigned NOT NULL AUTO_INCREMENT,period varchar(7) NOT NULL,currency varchar(12) NOT NULL DEFAULT 'USD',budget_amount bigint NOT NULL DEFAULT 0,allocated_amount bigint NOT NULL DEFAULT 0,eligible_watch_ms bigint unsigned NOT NULL DEFAULT 0,qualified_views bigint unsigned NOT NULL DEFAULT 0,status varchar(30) NOT NULL DEFAULT 'open',finalized_at datetime NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY period(period),KEY status(status)) {$c};");
		dbDelta("CREATE TABLE {$a} (id bigint unsigned NOT NULL AUTO_INCREMENT,period varchar(7) NOT NULL,creator_id bigint unsigned NOT NULL,object_type varchar(30) NOT NULL,object_id bigint unsigned NOT NULL,title varchar(255) NOT NULL DEFAULT '',qualified_views bigint unsigned NOT NULL DEFAULT 0,watch_ms bigint unsigned NOT NULL DEFAULT 0,amount bigint NOT NULL DEFAULT 0,status varchar(30) NOT NULL DEFAULT 'provisional',created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY period_object(period,creator_id,object_type,object_id),KEY creator_period(creator_id,period),KEY period_status(period,status)) {$c};");
		dbDelta("CREATE TABLE {$r} (id bigint unsigned NOT NULL AUTO_INCREMENT,entry_key varchar(191) NOT NULL,period varchar(7) NOT NULL DEFAULT '',entry_type varchar(30) NOT NULL DEFAULT 'deposit',amount bigint NOT NULL DEFAULT 0,currency varchar(12) NOT NULL DEFAULT 'USD',note varchar(255) NOT NULL DEFAULT '',created_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY entry_key(entry_key),KEY period(period),KEY entry_type(entry_type)) {$c};"); update_option(self::DB_OPTION,self::DB_VERSION,false);
	}
	public static function ensure_cron(){if(!wp_next_scheduled(self::CRON_HOOK))wp_schedule_event(time()+HOUR_IN_SECONDS,'hourly',self::CRON_HOOK);} public static function cron_sync(){ $s=self::settings(); if(self::enabled()&&'1'===(string)$s['auto_sync'])self::sync_period(gmdate('Y-m')); }
	public static function qualified_changed(){ if(!self::enabled()||get_transient('nfinite_video_sync_lock'))return; set_transient('nfinite_video_sync_lock',1,5*MINUTE_IN_SECONDS); self::sync_period(gmdate('Y-m')); }
	private static function valid_period($p){$p=sanitize_text_field((string)$p);return preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$p)?$p:'';} private static function bounds($p){$p=self::valid_period($p);if(!$p)return false;$d=DateTime::createFromFormat('!Y-m-d H:i:s',$p.'-01 00:00:00',new DateTimeZone('UTC'));$e=clone $d;$e->modify('+1 month');return array($d->format('Y-m-d H:i:s'),$e->format('Y-m-d H:i:s'));}
	public static function reserve_balance(){global $wpdb;$t=self::reserve_table();return(int)$wpdb->get_var("SELECT COALESCE(SUM(amount),0) FROM {$t}");}
	public static function period_row($p){global $wpdb;$t=self::periods_table();return$wpdb->get_row($wpdb->prepare("SELECT * FROM {$t} WHERE period=%s LIMIT 1",self::valid_period($p)),ARRAY_A);}
	public static function period_allocations($p,$creator=0){global $wpdb;$t=self::allocations_table();$p=self::valid_period($p);if($creator)return$wpdb->get_results($wpdb->prepare("SELECT * FROM {$t} WHERE period=%s AND creator_id=%d ORDER BY amount DESC,watch_ms DESC",$p,absint($creator)),ARRAY_A);return$wpdb->get_results($wpdb->prepare("SELECT * FROM {$t} WHERE period=%s ORDER BY amount DESC,watch_ms DESC",$p),ARRAY_A);}
	private static function monetized_object($type,$id,$creator){$type=sanitize_key($type);$id=absint($id);$creator=absint($creator);if('episode'===$type&&class_exists('Nfinite_Creators_Shows')&&Nfinite_Creators_Shows::EPISODE_POST_TYPE===get_post_type($id)){$owner=absint(get_post_meta($id,'_nfinite_episode_creator_id',true));if(!$owner){$show=absint(get_post_meta($id,'_nfinite_episode_show_id',true));$owner=$show?absint(get_post_meta($show,'_nfinite_show_creator_id',true)):0;}return$owner===$creator&&'monetized'===get_post_meta($id,'_nfinite_episode_video_monetization_status',true)?get_the_title($id):false;}if('video'===$type&&'nfinite_video'===get_post_type($id))return absint(get_post_meta($id,'_nfinite_video_creator_id',true))===$creator&&'monetized'===get_post_meta($id,'_nfinite_video_monetization_status',true)?get_the_title($id):false;return false;}
	public static function eligible_rows($p){if(!class_exists('Nfinite_Creators_Video_Engagement'))return array();$b=self::bounds($p);if(!$b)return array();global $wpdb;$t=Nfinite_Creators_Video_Engagement::table_name();$rows=$wpdb->get_results($wpdb->prepare("SELECT creator_id,object_type,object_id,COUNT(*) qualified_views,SUM(watched_ms) watch_ms FROM {$t} WHERE qualified=1 AND fraud_score<70 AND provider='youtube' AND started_at>=%s AND started_at<%s GROUP BY creator_id,object_type,object_id",$b[0],$b[1]),ARRAY_A);$out=array();foreach((array)$rows as$row){$title=self::monetized_object($row['object_type'],$row['object_id'],$row['creator_id']);if(!$title)continue;$out[]=array('creator_id'=>absint($row['creator_id']),'object_type'=>sanitize_key($row['object_type']),'object_id'=>absint($row['object_id']),'title'=>$title,'qualified_views'=>absint($row['qualified_views']),'watch_ms'=>absint($row['watch_ms']));}return$out;}
	private static function allocate($rows,$budget){$total=array_sum(array_map(function($r){return(int)$r['watch_ms'];},$rows));if(!$rows||$budget<=0||$total<=0)return array($rows,0,$total);$used=0;$f=array();foreach($rows as$i=>&$r){$x=$budget*(int)$r['watch_ms']/$total;$r['amount']=(int)floor($x);$f[$i]=$x-$r['amount'];$used+=$r['amount'];}unset($r);$rem=$budget-$used;arsort($f,SORT_NUMERIC);foreach(array_keys($f)as$i){if($rem<=0)break;$rows[$i]['amount']++;$rem--;}return array($rows,$budget,$total);}
	public static function sync_period($p){$p=self::valid_period($p);if(!$p)return new WP_Error('nfinite_video_period','Invalid period.');global$wpdb;$pt=self::periods_table();$at=self::allocations_table();$existing=self::period_row($p);if($existing&&'finalized'===$existing['status'])return$existing;$s=self::settings();$budget=min(max(0,(int)$s['monthly_budget_minor']),max(0,self::reserve_balance()));$rows=self::eligible_rows($p);list($rows,$allocated,$watch)=self::allocate($rows,$budget);$views=array_sum(array_map(function($r){return(int)$r['qualified_views'];},$rows));$now=current_time('mysql',true);$data=array('period'=>$p,'currency'=>strtoupper($s['currency']),'budget_amount'=>$budget,'allocated_amount'=>$allocated,'eligible_watch_ms'=>$watch,'qualified_views'=>$views,'status'=>'open','updated_at'=>$now);if($existing)$wpdb->update($pt,$data,array('id'=>absint($existing['id'])));else{$data['created_at']=$now;$wpdb->insert($pt,$data);} $seen=array();foreach($rows as$r){$k=$r['creator_id'].'|'.$r['object_type'].'|'.$r['object_id'];$seen[]=$k;$id=$wpdb->get_var($wpdb->prepare("SELECT id FROM {$at} WHERE period=%s AND creator_id=%d AND object_type=%s AND object_id=%d",$p,$r['creator_id'],$r['object_type'],$r['object_id']));$d=array('period'=>$p,'creator_id'=>$r['creator_id'],'object_type'=>$r['object_type'],'object_id'=>$r['object_id'],'title'=>$r['title'],'qualified_views'=>$r['qualified_views'],'watch_ms'=>$r['watch_ms'],'amount'=>$r['amount'],'status'=>'provisional','updated_at'=>$now);if($id)$wpdb->update($at,$d,array('id'=>absint($id)));else{$d['created_at']=$now;$wpdb->insert($at,$d);}}foreach(self::period_allocations($p)as$a){$k=$a['creator_id'].'|'.$a['object_type'].'|'.$a['object_id'];if(!in_array($k,$seen,true)&&'provisional'===$a['status'])$wpdb->delete($at,array('id'=>absint($a['id'])));}return self::period_row($p);}
	public static function finalize_period($p){$p=self::valid_period($p);$cur=self::sync_period($p);if(is_wp_error($cur)||'finalized'===($cur['status']??''))return$cur;global$wpdb;$tot=array();foreach(self::period_allocations($p)as$r){$c=absint($r['creator_id']);if(!isset($tot[$c]))$tot[$c]=array('amount'=>0,'views'=>0,'watch'=>0);$tot[$c]['amount']+=(int)$r['amount'];$tot[$c]['views']+=(int)$r['qualified_views'];$tot[$c]['watch']+=(int)$r['watch_ms'];}$now=current_time('mysql',true);foreach($tot as$c=>$v){if($v['amount']<=0)continue;$acct=class_exists('Nfinite_Creators_Commerce')?Nfinite_Creators_Commerce::creator_account_id($c,(int)get_post_field('post_author',$c)):'';Nfinite_Creators_Payments::record_earning(array('entry_key'=>'video_engagement:'.$p.':'.$c,'creator_id'=>$c,'source_type'=>'video_engagement','source_id'=>$p,'source_label'=>sprintf(__('PairOfDice video revenue statement — %s','nfinite-creators'),$p),'earning_kind'=>'content','accounting_period'=>$p,'currency'=>$cur['currency']?:'USD','eligible_amount'=>$v['amount'],'platform_fee_amount'=>0,'creator_amount'=>$v['amount'],'status'=>'finalized','earning_status'=>'finalized','payout_status'=>$acct?'pending':'blocked','is_provisional'=>0,'finalized_at'=>$now,'connected_account_id'=>$acct,'last_error'=>$acct?'':__('Connect Stripe to receive finalized video revenue share.','nfinite-creators')));}$wpdb->update(self::allocations_table(),array('status'=>'finalized','updated_at'=>$now),array('period'=>$p));$wpdb->update(self::periods_table(),array('status'=>'finalized','finalized_at'=>$now,'updated_at'=>$now),array('period'=>$p));if((int)$cur['allocated_amount']>0)$wpdb->replace(self::reserve_table(),array('entry_key'=>'period-allocation:'.$p,'period'=>$p,'entry_type'=>'allocation','amount'=>-(int)$cur['allocated_amount'],'currency'=>$cur['currency'],'note'=>'Finalized creator video revenue statements','created_at'=>$now));return self::period_row($p);}
	private static function pay_row($row){if(!class_exists('Nfinite_Creators_Commerce')||!Nfinite_Creators_Commerce::enabled())return new WP_Error('stripe_disabled','Stripe Connect is not enabled.');if(!empty($row['transfer_id']))return$row;$c=absint($row['creator_id']);$amount=max(0,(int)$row['creator_amount']-(int)$row['reversed_amount']);$acct=Nfinite_Creators_Commerce::creator_account_id($c,(int)get_post_field('post_author',$c));if(!$acct){Nfinite_Creators_Payments::update_earning_entry($row['entry_key'],array('status'=>'blocked','payout_status'=>'blocked','last_error'=>'Creator has not connected Stripe.'));return new WP_Error('no_account','Creator has not connected Stripe.');}$status=Nfinite_Creators_Commerce::cached_status($c,(int)get_post_field('post_author',$c));if('active'!==($status['transfer_status']??'')){$remote=Nfinite_Creators_Commerce::sync_account_status($c,(int)get_post_field('post_author',$c),$acct);if(!is_wp_error($remote))$status=$remote;}if('active'!==($status['transfer_status']??''))return new WP_Error('account_blocked','Creator Stripe account is not enabled for transfers.');$payload=array('amount'=>$amount,'currency'=>strtolower($row['currency']?:'USD'),'destination'=>$acct,'transfer_group'=>'NFINITE_VIDEO_'.str_replace('-','_',$row['accounting_period']),'description'=>'PairOfDice video revenue share - '.$row['accounting_period'],'metadata'=>array('nfinite_creator_id'=>(string)$c,'accounting_period'=>(string)$row['accounting_period'],'source_type'=>'video_engagement'));$tr=Nfinite_Creators_Payments::stripe_request('POST','/v1/transfers',$payload,array('Idempotency-Key'=>'nfinite_video_'.$row['accounting_period'].'_'.$c.'_'.$amount));if(is_wp_error($tr)){Nfinite_Creators_Payments::update_earning_entry($row['entry_key'],array('status'=>'failed','payout_status'=>'failed','last_error'=>$tr->get_error_message()));return$tr;}Nfinite_Creators_Payments::update_earning_entry($row['entry_key'],array('connected_account_id'=>$acct,'transfer_group'=>$payload['transfer_group'],'transfer_id'=>sanitize_text_field($tr['id']??''),'status'=>'transferred','payout_status'=>'transferred','last_error'=>''));return$tr;}
	public static function pay_period($p){$p=self::valid_period($p);$pr=self::period_row($p);if(!$pr||'finalized'!==$pr['status'])return new WP_Error('not_finalized','Finalize the period first.');global$wpdb;$lt=Nfinite_Creators_Payments::table_name();$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$lt} WHERE source_type='video_engagement' AND accounting_period=%s ORDER BY creator_id",$p),ARRAY_A);$out=array();foreach($rows as$r)$out[absint($r['creator_id'])]=self::pay_row($r);return$out;}
	public static function creator_summary($creator,$p=''){ $p=self::valid_period($p?:gmdate('Y-m'));$a=self::period_allocations($p,$creator);$amount=$views=$watch=0;$status='none';foreach($a as$r){$amount+=(int)$r['amount'];$views+=(int)$r['qualified_views'];$watch+=(int)$r['watch_ms'];$status=$r['status'];}return array('period'=>$p,'qualified_views'=>$views,'watch_ms'=>$watch,'amount_minor'=>$amount,'status'=>$status,'allocations'=>$a); }
	private static function money($minor,$currency='USD'){$major=Nfinite_Creators_Payments::from_minor((int)$minor,$currency);return function_exists('wc_price')?wc_price($major,array('currency'=>$currency)):'$'.number_format_i18n($major,2);} public static function admin_menu(){add_submenu_page('edit.php?post_type=nfinite_creator',__('Video Revenue Share','nfinite-creators'),__('Video Revenue Share','nfinite-creators'),'manage_options','nfinite-video-earnings',array(__CLASS__,'admin_page'));}
	public static function admin_page(){if(!current_user_can('manage_options'))return;$s=self::settings();$p=isset($_GET['period'])?self::valid_period(wp_unslash($_GET['period'])):gmdate('Y-m');if(!$p)$p=gmdate('Y-m');$row=self::period_row($p);$alloc=self::period_allocations($p);$tot=array();foreach($alloc as$a){$c=absint($a['creator_id']);if(!isset($tot[$c]))$tot[$c]=array('views'=>0,'watch'=>0,'amount'=>0);$tot[$c]['views']+=(int)$a['qualified_views'];$tot[$c]['watch']+=(int)$a['watch_ms'];$tot[$c]['amount']+=(int)$a['amount'];}?>
	<div class="wrap"><h1><?php esc_html_e('Nfinite Video Revenue Share','nfinite-creators');?></h1><p><?php esc_html_e('Allocates an internal monthly video reserve by eligible qualified YouTube watch time. YouTube platform revenue remains separate from PairOfDice revenue share.','nfinite-creators');?></p><?php if(isset($_GET['nfinite_video_notice'])):?><div class="notice notice-success"><p><?php echo esc_html(sanitize_text_field(wp_unslash($_GET['nfinite_video_notice'])));?></p></div><?php endif;?><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;max-width:900px"><div class="card"><h2>Internal reserve</h2><p style="font-size:24px"><strong><?php echo wp_kses_post(self::money(self::reserve_balance(),$s['currency']));?></strong></p></div><div class="card"><h2><?php echo esc_html($p);?></h2><p style="font-size:24px"><strong><?php echo wp_kses_post(self::money($row?$row['allocated_amount']:0,$s['currency']));?></strong></p><p><?php echo esc_html(number_format_i18n($row?$row['qualified_views']:0));?> qualified views • <?php echo esc_html(number_format_i18n(($row?$row['eligible_watch_ms']:0)/3600000,2));?> hours</p></div></div>
	<h2>Program settings</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="nfinite_video_save_settings"><?php wp_nonce_field('nfinite_video_save_settings');?><table class="form-table"><tr><th>Enable video revenue share</th><td><label><input type="checkbox" name="enabled" value="1" <?php checked($s['enabled'],'1');?>> Calculate provisional earnings from qualified, approved YouTube watch time</label></td></tr><tr><th>Monthly allocation cap</th><td><input type="number" min="0" step="0.01" name="monthly_budget" value="<?php echo esc_attr(number_format(Nfinite_Creators_Payments::from_minor((int)$s['monthly_budget_minor'],$s['currency']),2,'.',''));?>"> <?php echo esc_html($s['currency']);?></td></tr><tr><th>Automatic sync</th><td><label><input type="checkbox" name="auto_sync" value="1" <?php checked($s['auto_sync'],'1');?>> Refresh open period automatically</label></td></tr></table><?php submit_button('Save video settings');?></form>
	<h2>Add to internal video reserve</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" style="display:flex;gap:8px;align-items:end"><input type="hidden" name="action" value="nfinite_video_add_reserve"><?php wp_nonce_field('nfinite_video_add_reserve');?><label>Amount<br><input required type="number" min="0.01" step="0.01" name="amount"></label><label>Note<br><input type="text" name="note" class="regular-text"></label><?php submit_button('Add reserve','secondary','submit',false);?></form>
	<hr><h2>Accounting period</h2><form method="get"><input type="hidden" name="post_type" value="nfinite_creator"><input type="hidden" name="page" value="nfinite-video-earnings"><input type="month" name="period" value="<?php echo esc_attr($p);?>"> <button class="button">View</button></form><div style="display:flex;gap:8px;margin:12px 0"><?php foreach(array('sync_period'=>'Sync provisional earnings','finalize_period'=>'Finalize period','pay_period'=>'Pay finalized statements')as$act=>$label):?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="nfinite_video_<?php echo esc_attr($act);?>"><input type="hidden" name="period" value="<?php echo esc_attr($p);?>"><?php wp_nonce_field('nfinite_video_'.$act);?><button class="button<?php echo 'sync_period'===$act?' button-primary':'';?>" <?php if('sync_period'!==$act&&(!$row||('pay_period'===$act&&'finalized'!==$row['status'])))disabled(true);?>><?php echo esc_html($label);?></button></form><?php endforeach;?></div>
	<table class="widefat striped"><thead><tr><th>Creator</th><th>Qualified views</th><th>Watch hours</th><th>Statement</th></tr></thead><tbody><?php if(!$tot):?><tr><td colspan="4">No eligible monetized qualified video engagement yet.</td></tr><?php else:foreach($tot as$c=>$v):?><tr><td><?php echo esc_html(get_the_title($c));?></td><td><?php echo esc_html(number_format_i18n($v['views']));?></td><td><?php echo esc_html(number_format_i18n($v['watch']/3600000,2));?></td><td><?php echo wp_kses_post(self::money($v['amount'],$s['currency']));?></td></tr><?php endforeach;endif;?></tbody></table></div><?php }

	public static function monetization_statuses(){ return array('not_enrolled'=>'Not Enrolled','pending_review'=>'Pending Review','monetized'=>'Monetized','ineligible'=>'Ineligible','suspended'=>'Suspended'); }
	public static function add_monetization_box(){ add_meta_box('nfinite_video_revenue_share',__('PairOfDice Video Revenue Share','nfinite-creators'),array(__CLASS__,'render_monetization_box'),null,'side','high'); }
	public static function render_monetization_box($post){ wp_nonce_field('nfinite_video_monetization_save','nfinite_video_monetization_nonce'); $key='nfinite_episode'===$post->post_type?'_nfinite_episode_video_monetization_status':'_nfinite_video_monetization_status'; $status=get_post_meta($post->ID,$key,true)?:'not_enrolled'; $rights='nfinite_episode'===$post->post_type?(bool)get_post_meta($post->ID,'_nfinite_episode_video_rights_confirmed',true):true; echo '<p><label><strong>'.esc_html__('Status','nfinite-creators').'</strong><br><select class="widefat" name="nfinite_video_monetization_status">'; foreach(self::monetization_statuses() as$k=>$v)echo '<option value="'.esc_attr($k).'" '.selected($status,$k,false).'>'.esc_html($v).'</option>'; echo '</select></label></p>'; if('nfinite_episode'===$post->post_type)echo '<p><label><input type="checkbox" name="nfinite_video_rights_confirmed" value="1" '.checked($rights,true,false).'> '.esc_html__('Creator confirmed they control the necessary rights and authorize PairOfDice revenue share.','nfinite-creators').'</label></p>'; echo '<p class="description">'.esc_html__('Only Monetized YouTube content can enter monthly PairOfDice video revenue-share accounting.','nfinite-creators').'</p>'; }
	public static function save_monetization_box($post_id,$post){ if(!isset($_POST['nfinite_video_monetization_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nfinite_video_monetization_nonce'])),'nfinite_video_monetization_save')||!current_user_can('manage_options'))return; $status=sanitize_key(wp_unslash($_POST['nfinite_video_monetization_status']??'not_enrolled')); if(!isset(self::monetization_statuses()[$status]))$status='not_enrolled'; $key='nfinite_episode'===$post->post_type?'_nfinite_episode_video_monetization_status':'_nfinite_video_monetization_status'; update_post_meta($post_id,$key,$status); if('nfinite_episode'===$post->post_type)update_post_meta($post_id,'_nfinite_episode_video_rights_confirmed',!empty($_POST['nfinite_video_rights_confirmed'])?1:0); }

	private static function redirect($msg,$p=''){$url=add_query_arg(array('post_type'=>'nfinite_creator','page'=>'nfinite-video-earnings','nfinite_video_notice'=>$msg),admin_url('edit.php'));if($p)$url=add_query_arg('period',$p,$url);wp_safe_redirect($url);exit;}
	public static function admin_save_settings(){if(!current_user_can('manage_options'))wp_die('Forbidden');check_admin_referer('nfinite_video_save_settings');$s=self::settings();$s['enabled']=isset($_POST['enabled'])?'1':'0';$s['auto_sync']=isset($_POST['auto_sync'])?'1':'0';$s['monthly_budget_minor']=Nfinite_Creators_Payments::to_minor(max(0,(float)($_POST['monthly_budget']??0)),$s['currency']);update_option(self::OPTION_KEY,$s,false);self::redirect('Video revenue share settings saved.');}
	public static function admin_add_reserve(){if(!current_user_can('manage_options'))wp_die('Forbidden');check_admin_referer('nfinite_video_add_reserve');$s=self::settings();$minor=Nfinite_Creators_Payments::to_minor(max(0,(float)($_POST['amount']??0)),$s['currency']);if($minor<=0)self::redirect('Amount must be greater than zero.');global$wpdb;$wpdb->insert(self::reserve_table(),array('entry_key'=>'deposit:'.wp_generate_uuid4(),'period'=>'','entry_type'=>'deposit','amount'=>$minor,'currency'=>$s['currency'],'note'=>sanitize_text_field(wp_unslash($_POST['note']??'')),'created_at'=>current_time('mysql',true)));self::redirect('Internal video reserve updated.');}
	public static function admin_sync_period(){if(!current_user_can('manage_options'))wp_die('Forbidden');check_admin_referer('nfinite_video_sync_period');$p=self::valid_period($_POST['period']??'');$r=self::sync_period($p);self::redirect(is_wp_error($r)?$r->get_error_message():'Provisional video earnings synced.',$p);} public static function admin_finalize_period(){if(!current_user_can('manage_options'))wp_die('Forbidden');check_admin_referer('nfinite_video_finalize_period');$p=self::valid_period($_POST['period']??'');$r=self::finalize_period($p);self::redirect(is_wp_error($r)?$r->get_error_message():'Video accounting period finalized.',$p);} public static function admin_pay_period(){if(!current_user_can('manage_options'))wp_die('Forbidden');check_admin_referer('nfinite_video_pay_period');$p=self::valid_period($_POST['period']??'');$r=self::pay_period($p);self::redirect(is_wp_error($r)?$r->get_error_message():'Video statement payouts processed.',$p);}
}
