<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/** Organizations, rosters and delegated team access. */
class Nfinite_Creators_Organizations {
	const CPT = 'nfinite_org';
	const REL = 'nfinite_org_member';
	const TEAM = 'nfinite_org_team';

	public static function init() {
		add_action( 'init', array( __CLASS__, 'register' ) );
		add_action( 'add_meta_boxes', array( __CLASS__, 'meta_boxes' ) );
		add_action( 'save_post_' . self::CPT, array( __CLASS__, 'save_org' ), 10, 2 );
		add_action( 'save_post_' . self::REL, array( __CLASS__, 'save_relation' ), 10, 2 );
		add_action( 'save_post_' . self::TEAM, array( __CLASS__, 'save_team' ), 10, 2 );
		add_shortcode( 'nfinite_organizations', array( __CLASS__, 'directory_shortcode' ) );
		add_shortcode( 'nfinite_organization_roster', array( __CLASS__, 'roster_shortcode' ) );
		add_shortcode( 'nfinite_organization_studio', array( __CLASS__, 'studio_shortcode' ) );
		add_action( 'admin_post_nfinite_org_save', array( __CLASS__, 'frontend_save' ) );
		add_filter( 'the_content', array( __CLASS__, 'public_profile' ), 20 );
	}

	public static function register() {
		register_post_type( self::CPT, array(
			'labels'=>array('name'=>__('Organizations','nfinite-creators'),'singular_name'=>__('Organization','nfinite-creators'),'add_new_item'=>__('Add Organization','nfinite-creators'),'edit_item'=>__('Edit Organization','nfinite-creators')),
			'public'=>true,'show_in_rest'=>true,'has_archive'=>true,'rewrite'=>array('slug'=>'organizations','with_front'=>false),'menu_icon'=>'dashicons-building','supports'=>array('title','editor','excerpt','thumbnail','author','revisions'),'show_in_menu'=>'edit.php?post_type=nfinite_creator'
		) );
		register_taxonomy( 'nfinite_org_type', array(self::CPT), array('public'=>true,'show_in_rest'=>true,'hierarchical'=>false,'labels'=>array('name'=>__('Organization Types','nfinite-creators'),'singular_name'=>__('Organization Type','nfinite-creators')),'rewrite'=>array('slug'=>'organization-type','with_front'=>false)) );
		foreach ( array('Label','Management','Agency','Podcast Network','Media Company','Collective','Studio','Promoter') as $term ) if ( ! term_exists($term,'nfinite_org_type') ) wp_insert_term($term,'nfinite_org_type');
		$private = array('public'=>false,'show_ui'=>true,'show_in_rest'=>false,'show_in_menu'=>'edit.php?post_type=nfinite_creator','supports'=>array('title'),'capability_type'=>'post');
		register_post_type( self::REL, array_merge($private,array('labels'=>array('name'=>__('Roster Relationships','nfinite-creators'),'singular_name'=>__('Roster Relationship','nfinite-creators')))) );
		register_post_type( self::TEAM, array_merge($private,array('labels'=>array('name'=>__('Organization Team','nfinite-creators'),'singular_name'=>__('Team Member','nfinite-creators')))) );
	}

	public static function meta_boxes() {
		add_meta_box('nfinite_org_details',__('Organization Details','nfinite-creators'),array(__CLASS__,'org_box'),self::CPT,'normal','high');
		add_meta_box('nfinite_org_roster_rel',__('Roster Relationship','nfinite-creators'),array(__CLASS__,'relation_box'),self::REL,'normal','high');
		add_meta_box('nfinite_org_team_member',__('Organization Team Member','nfinite-creators'),array(__CLASS__,'team_box'),self::TEAM,'normal','high');
	}
	private static function field($id,$label,$value='',$type='text') { echo '<p><label><strong>'.esc_html($label).'</strong><br><input style="width:100%" type="'.esc_attr($type).'" name="'.esc_attr($id).'" value="'.esc_attr($value).'"></label></p>'; }
	public static function org_box($post) {
		wp_nonce_field('nfinite_org_save','nfinite_org_nonce');
		self::field('_nfinite_org_website',__('Website','nfinite-creators'),get_post_meta($post->ID,'_nfinite_org_website',true),'url');
		self::field('_nfinite_org_location',__('Location','nfinite-creators'),get_post_meta($post->ID,'_nfinite_org_location',true));
		self::field('_nfinite_org_contact_email',__('Public contact email','nfinite-creators'),get_post_meta($post->ID,'_nfinite_org_contact_email',true),'email');
		echo '<p><label><strong>'.esc_html__('Tagline','nfinite-creators').'</strong><br><input style="width:100%" name="_nfinite_org_tagline" value="'.esc_attr(get_post_meta($post->ID,'_nfinite_org_tagline',true)).'"></label></p>';
		echo '<p class="description">'.esc_html__('The post author is the primary organization owner. Add roster relationships and delegated team members from the Creators admin menu.','nfinite-creators').'</p>';
	}
	public static function relation_box($post) {
		wp_nonce_field('nfinite_org_rel_save','nfinite_org_rel_nonce'); $org=(int)get_post_meta($post->ID,'_nfinite_org_id',true); $creator=(int)get_post_meta($post->ID,'_nfinite_creator_id',true);
		self::select_posts('_nfinite_org_id',__('Organization','nfinite-creators'),self::CPT,$org); self::select_posts('_nfinite_creator_id',__('Creator','nfinite-creators'),'nfinite_creator',$creator);
		self::field('_nfinite_roster_role',__('Roster role / title','nfinite-creators'),get_post_meta($post->ID,'_nfinite_roster_role',true));
		echo '<p><label><strong>'.esc_html__('Relationship status','nfinite-creators').'</strong><br><select name="_nfinite_roster_status">'; foreach(array('active'=>'Active','pending'=>'Pending','former'=>'Former') as $k=>$v) echo '<option value="'.esc_attr($k).'" '.selected(get_post_meta($post->ID,'_nfinite_roster_status',true),$k,false).'>'.esc_html($v).'</option>'; echo '</select></label></p>';
	}
	public static function team_box($post) {
		wp_nonce_field('nfinite_org_team_save','nfinite_org_team_nonce'); self::select_posts('_nfinite_org_id',__('Organization','nfinite-creators'),self::CPT,(int)get_post_meta($post->ID,'_nfinite_org_id',true));
		self::field('_nfinite_org_user_email',__('WordPress user email','nfinite-creators'),get_post_meta($post->ID,'_nfinite_org_user_email',true),'email');
		echo '<p><label><strong>'.esc_html__('Team role','nfinite-creators').'</strong><br><select name="_nfinite_org_team_role">'; foreach(array('admin'=>'Admin','editor'=>'Editor','analyst'=>'Analyst') as $k=>$v) echo '<option value="'.esc_attr($k).'" '.selected(get_post_meta($post->ID,'_nfinite_org_team_role',true),$k,false).'>'.esc_html($v).'</option>'; echo '</select></label></p>';
	}
	private static function select_posts($name,$label,$type,$selected) { $items=get_posts(array('post_type'=>$type,'post_status'=>array('publish','draft','pending'),'posts_per_page'=>-1,'orderby'=>'title','order'=>'ASC')); echo '<p><label><strong>'.esc_html($label).'</strong><br><select name="'.esc_attr($name).'" style="width:100%"><option value="">'.esc_html__('Select…','nfinite-creators').'</option>'; foreach($items as $p) echo '<option value="'.(int)$p->ID.'" '.selected($selected,$p->ID,false).'>'.esc_html($p->post_title).'</option>'; echo '</select></label></p>'; }
	public static function save_org($id,$post) { if(!isset($_POST['nfinite_org_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nfinite_org_nonce'])),'nfinite_org_save')||!current_user_can('edit_post',$id))return; foreach(array('_nfinite_org_website'=>'esc_url_raw','_nfinite_org_location'=>'sanitize_text_field','_nfinite_org_contact_email'=>'sanitize_email','_nfinite_org_tagline'=>'sanitize_text_field') as $k=>$fn) if(isset($_POST[$k])) update_post_meta($id,$k,call_user_func($fn,wp_unslash($_POST[$k]))); }
	public static function save_relation($id,$post) { if(!isset($_POST['nfinite_org_rel_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nfinite_org_rel_nonce'])),'nfinite_org_rel_save')||!current_user_can('edit_post',$id))return; foreach(array('_nfinite_org_id','_nfinite_creator_id') as $k) if(isset($_POST[$k])) update_post_meta($id,$k,absint($_POST[$k])); if(isset($_POST['_nfinite_roster_role']))update_post_meta($id,'_nfinite_roster_role',sanitize_text_field(wp_unslash($_POST['_nfinite_roster_role']))); if(isset($_POST['_nfinite_roster_status']))update_post_meta($id,'_nfinite_roster_status',sanitize_key($_POST['_nfinite_roster_status'])); self::sync_title($id); }
	public static function save_team($id,$post) { if(!isset($_POST['nfinite_org_team_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nfinite_org_team_nonce'])),'nfinite_org_team_save')||!current_user_can('edit_post',$id))return; if(isset($_POST['_nfinite_org_id']))update_post_meta($id,'_nfinite_org_id',absint($_POST['_nfinite_org_id'])); if(isset($_POST['_nfinite_org_user_email'])) { $email=sanitize_email(wp_unslash($_POST['_nfinite_org_user_email'])); update_post_meta($id,'_nfinite_org_user_email',$email); $u=get_user_by('email',$email); update_post_meta($id,'_nfinite_org_user_id',$u?(int)$u->ID:0); } if(isset($_POST['_nfinite_org_team_role']))update_post_meta($id,'_nfinite_org_team_role',sanitize_key($_POST['_nfinite_org_team_role'])); self::sync_title($id); }
	private static function sync_title($id) { if(get_post_type($id)===self::REL){$a=get_the_title((int)get_post_meta($id,'_nfinite_creator_id',true));$b=get_the_title((int)get_post_meta($id,'_nfinite_org_id',true));}else{$a=get_post_meta($id,'_nfinite_org_user_email',true);$b=get_the_title((int)get_post_meta($id,'_nfinite_org_id',true));} if($a||$b){remove_action('save_post_'.get_post_type($id),array(__CLASS__,get_post_type($id)===self::REL?'save_relation':'save_team'),10);wp_update_post(array('ID'=>$id,'post_title'=>trim($a.' — '.$b)));} }

	public static function roster($org_id) { $rels=get_posts(array('post_type'=>self::REL,'post_status'=>'publish','posts_per_page'=>-1,'meta_query'=>array(array('key'=>'_nfinite_org_id','value'=>(int)$org_id),array('key'=>'_nfinite_roster_status','value'=>'active')))); $out=array(); foreach($rels as $r){$c=get_post((int)get_post_meta($r->ID,'_nfinite_creator_id',true));if($c&&'nfinite_creator'===$c->post_type)$out[]=array('creator'=>$c,'role'=>get_post_meta($r->ID,'_nfinite_roster_role',true));} return $out; }
	public static function user_orgs($user_id=0) { $user_id=$user_id?:get_current_user_id(); $ids=array(); $owned=get_posts(array('post_type'=>self::CPT,'author'=>$user_id,'post_status'=>array('publish','draft','pending'),'posts_per_page'=>-1,'fields'=>'ids')); $ids=array_merge($ids,$owned); $teams=get_posts(array('post_type'=>self::TEAM,'post_status'=>'publish','posts_per_page'=>-1,'meta_key'=>'_nfinite_org_user_id','meta_value'=>$user_id)); foreach($teams as $t)$ids[]=(int)get_post_meta($t->ID,'_nfinite_org_id',true); return array_values(array_unique(array_filter($ids))); }
	public static function can_manage($org_id,$user_id=0,$need='editor') { $user_id=$user_id?:get_current_user_id(); if(user_can($user_id,'manage_options'))return true; if((int)get_post_field('post_author',$org_id)===$user_id)return true; $rank=array('analyst'=>1,'editor'=>2,'admin'=>3); $need_rank=isset($rank[$need])?$rank[$need]:2; $teams=get_posts(array('post_type'=>self::TEAM,'post_status'=>'publish','posts_per_page'=>-1,'meta_query'=>array(array('key'=>'_nfinite_org_id','value'=>$org_id),array('key'=>'_nfinite_org_user_id','value'=>$user_id)))); foreach($teams as $t)if(($rank[get_post_meta($t->ID,'_nfinite_org_team_role',true)]??0)>=$need_rank)return true; return false; }

	public static function directory_shortcode($atts) { $atts=shortcode_atts(array('limit'=>24),$atts); $q=get_posts(array('post_type'=>self::CPT,'post_status'=>'publish','posts_per_page'=>absint($atts['limit']))); ob_start(); echo '<div class="nfinite-org-grid">'; foreach($q as $o){echo '<article class="nfinite-org-card">'.get_the_post_thumbnail($o->ID,'medium').'<h3><a href="'.esc_url(get_permalink($o)).'">'.esc_html($o->post_title).'</a></h3><p>'.esc_html(get_post_meta($o->ID,'_nfinite_org_tagline',true)).'</p><small>'.sprintf(esc_html__('%d roster members','nfinite-creators'),count(self::roster($o->ID))).'</small></article>';} echo '</div>'; return ob_get_clean(); }
	public static function roster_shortcode($atts) { $atts=shortcode_atts(array('organization_id'=>get_the_ID()),$atts); return self::render_roster(absint($atts['organization_id'])); }
	private static function render_roster($id) { $rows=self::roster($id); if(!$rows)return '<p>'.esc_html__('No active roster members yet.','nfinite-creators').'</p>'; ob_start(); echo '<div class="nfinite-org-roster">'; foreach($rows as $r){$c=$r['creator'];echo '<article class="nfinite-org-roster__member"><a href="'.esc_url(get_permalink($c)).'">'.get_the_post_thumbnail($c->ID,'thumbnail').'<strong>'.esc_html($c->post_title).'</strong></a>';if($r['role'])echo '<span>'.esc_html($r['role']).'</span>';echo '</article>';} echo '</div>'; return ob_get_clean(); }
	public static function public_profile($content) { if(!is_singular(self::CPT)||!in_the_loop()||!is_main_query())return $content; $id=get_the_ID(); $types=get_the_terms($id,'nfinite_org_type'); $meta='<section class="nfinite-org-profile-meta">'; if($types&&!is_wp_error($types))$meta.='<span>'.esc_html(implode(', ',wp_list_pluck($types,'name'))).'</span>'; $loc=get_post_meta($id,'_nfinite_org_location',true);if($loc)$meta.='<span>'.esc_html($loc).'</span>'; $web=get_post_meta($id,'_nfinite_org_website',true);if($web)$meta.='<a href="'.esc_url($web).'" rel="noopener">'.esc_html__('Website','nfinite-creators').'</a>'; $meta.='</section><section class="nfinite-org-profile-roster"><h2>'.esc_html__('Roster','nfinite-creators').'</h2>'.self::render_roster($id).'</section>'; return $content.$meta; }

	public static function studio_shortcode() { if(!is_user_logged_in())return '<p>'.esc_html__('Log in to manage organizations.','nfinite-creators').'</p>'; $orgs=self::user_orgs(); if(!$orgs)return '<section class="nfinite-org-studio"><h2>'.esc_html__('Organization Studio','nfinite-creators').'</h2><p>'.esc_html__('You do not currently manage an organization. An administrator can create an organization and assign you as its owner or team member.','nfinite-creators').'</p></section>'; $selected=isset($_GET['nfinite_org_id'])?absint($_GET['nfinite_org_id']):$orgs[0]; if(!in_array($selected,$orgs,true)&&!current_user_can('manage_options'))$selected=$orgs[0]; $org=get_post($selected); ob_start(); echo '<section class="nfinite-org-studio"><div class="nfinite-org-studio__head"><div><span class="nfinite-eyebrow">'.esc_html__('Organization Studio','nfinite-creators').'</span><h2>'.esc_html($org->post_title).'</h2></div><form method="get"><select name="nfinite_org_id" onchange="this.form.submit()">';foreach($orgs as $oid)echo '<option value="'.(int)$oid.'" '.selected($selected,$oid,false).'>'.esc_html(get_the_title($oid)).'</option>';echo '</select></form></div>'; echo '<div class="nfinite-org-studio__stats"><div><strong>'.count(self::roster($selected)).'</strong><span>'.esc_html__('Roster','nfinite-creators').'</span></div><div><strong>'.count(get_posts(array('post_type'=>self::TEAM,'post_status'=>'publish','posts_per_page'=>-1,'meta_key'=>'_nfinite_org_id','meta_value'=>$selected))).'</strong><span>'.esc_html__('Team','nfinite-creators').'</span></div></div>'; echo '<h3>'.esc_html__('Roster','nfinite-creators').'</h3>'.self::render_roster($selected); if(self::can_manage($selected,get_current_user_id(),'editor')){echo '<form class="nfinite-org-studio__form" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="nfinite_org_save"><input type="hidden" name="org_id" value="'.(int)$selected.'">';wp_nonce_field('nfinite_org_frontend_save','nfinite_org_frontend_nonce');echo '<h3>'.esc_html__('Organization profile','nfinite-creators').'</h3><label>'.esc_html__('Tagline','nfinite-creators').'<input name="tagline" value="'.esc_attr(get_post_meta($selected,'_nfinite_org_tagline',true)).'"></label><label>'.esc_html__('Location','nfinite-creators').'<input name="location" value="'.esc_attr(get_post_meta($selected,'_nfinite_org_location',true)).'"></label><label>'.esc_html__('Website','nfinite-creators').'<input type="url" name="website" value="'.esc_attr(get_post_meta($selected,'_nfinite_org_website',true)).'"></label><button class="nfinite-btn" type="submit">'.esc_html__('Save organization','nfinite-creators').'</button></form>';} echo '</section>'; return ob_get_clean(); }
	public static function frontend_save() { if(!is_user_logged_in()||!isset($_POST['nfinite_org_frontend_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nfinite_org_frontend_nonce'])),'nfinite_org_frontend_save'))wp_die(esc_html__('Invalid request.','nfinite-creators')); $id=absint($_POST['org_id']??0);if(!$id||!self::can_manage($id,get_current_user_id(),'editor'))wp_die(esc_html__('You cannot manage this organization.','nfinite-creators')); update_post_meta($id,'_nfinite_org_tagline',sanitize_text_field(wp_unslash($_POST['tagline']??'')));update_post_meta($id,'_nfinite_org_location',sanitize_text_field(wp_unslash($_POST['location']??'')));update_post_meta($id,'_nfinite_org_website',esc_url_raw(wp_unslash($_POST['website']??'')));wp_safe_redirect(add_query_arg(array('nfinite_org_id'=>$id,'nfinite_org_saved'=>1),wp_get_referer()?:home_url('/')));exit; }
}
