<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/** Creator Opportunities + Brand Deals V1. */
class Nfinite_Creators_Opportunities {
	const OPPORTUNITY = 'nfinite_opportunity';
	const APPLICATION = 'nfinite_brand_app';

	public static function init() {
		add_action('init',array(__CLASS__,'register_types'));
		add_action('add_meta_boxes',array(__CLASS__,'boxes'));
		add_action('save_post_'.self::OPPORTUNITY,array(__CLASS__,'save_opportunity'));
		add_action('save_post_'.self::APPLICATION,array(__CLASS__,'save_application'));
		add_shortcode('nfinite_opportunities',array(__CLASS__,'shortcode'));
		add_action('admin_post_nfinite_apply_opportunity',array(__CLASS__,'apply'));
		add_action('admin_post_nopriv_nfinite_apply_opportunity',array(__CLASS__,'login_required'));
		add_filter('manage_'.self::OPPORTUNITY.'_posts_columns',array(__CLASS__,'opp_columns'));
		add_action('manage_'.self::OPPORTUNITY.'_posts_custom_column',array(__CLASS__,'opp_column'),10,2);
	}
	public static function register_types() {
		register_post_type(self::OPPORTUNITY,array('labels'=>array('name'=>'Brand Opportunities','singular_name'=>'Brand Opportunity','add_new_item'=>'Add Brand Opportunity','edit_item'=>'Edit Brand Opportunity'),'public'=>true,'show_in_rest'=>true,'show_in_menu'=>'edit.php?post_type=nfinite_creator','supports'=>array('title','editor','thumbnail'),'rewrite'=>array('slug'=>'opportunities'),'has_archive'=>true));
		register_post_type(self::APPLICATION,array('labels'=>array('name'=>'Brand Applications','singular_name'=>'Brand Application'),'public'=>false,'show_ui'=>true,'show_in_menu'=>'edit.php?post_type=nfinite_creator','supports'=>array('title'),'capability_type'=>'post'));
	}
	public static function boxes(){
		add_meta_box('nfinite_opportunity_terms','Opportunity Terms',array(__CLASS__,'opp_box'),self::OPPORTUNITY,'normal','high');
		add_meta_box('nfinite_brand_application','Application / Deal',array(__CLASS__,'app_box'),self::APPLICATION,'normal','high');
	}
	private static function field($key,$label,$type='text',$post_id=0){$v=get_post_meta($post_id,$key,true);echo '<p><label><strong>'.esc_html($label).'</strong></label><br><input style="width:100%" type="'.esc_attr($type).'" name="'.esc_attr($key).'" value="'.esc_attr($v).'" /></p>';}
	public static function opp_box($p){wp_nonce_field('nfinite_opportunity_save','nfinite_opportunity_nonce');self::field('_nfinite_opp_brand','Brand / Sponsor','text',$p->ID);self::field('_nfinite_opp_campaign','Linked Campaign ID','number',$p->ID);self::field('_nfinite_opp_compensation','Compensation per selected creator (USD)','number',$p->ID);self::field('_nfinite_opp_deadline','Application deadline','date',$p->ID);self::field('_nfinite_opp_slots','Creator slots','number',$p->ID);self::field('_nfinite_opp_deliverables','Deliverables','text',$p->ID);$status=get_post_meta($p->ID,'_nfinite_opp_status',true)?:'draft';echo '<p><strong>Status</strong><br><select name="_nfinite_opp_status">';foreach(array('draft','open','closed','completed') as $s)echo '<option value="'.esc_attr($s).'" '.selected($status,$s,false).'>'.esc_html(ucwords($s)).'</option>';echo '</select></p>';echo '<p class="description">Publish + Open makes this opportunity available to eligible logged-in creators. Compensation is written to Creator Earnings only after an application is marked Approved.</p>';}
	public static function save_opportunity($id){if(!isset($_POST['nfinite_opportunity_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nfinite_opportunity_nonce'])),'nfinite_opportunity_save')||!current_user_can('edit_post',$id))return;foreach(array('_nfinite_opp_brand','_nfinite_opp_deliverables','_nfinite_opp_status','_nfinite_opp_deadline') as $k)if(isset($_POST[$k]))update_post_meta($id,$k,sanitize_text_field(wp_unslash($_POST[$k])));foreach(array('_nfinite_opp_campaign','_nfinite_opp_slots') as $k)if(isset($_POST[$k]))update_post_meta($id,$k,absint($_POST[$k]));if(isset($_POST['_nfinite_opp_compensation']))update_post_meta($id,'_nfinite_opp_compensation',number_format(max(0,(float)$_POST['_nfinite_opp_compensation']),2,'.',''));}
	public static function app_box($p){wp_nonce_field('nfinite_brand_app_save','nfinite_brand_app_nonce');$oid=absint(get_post_meta($p->ID,'_nfinite_app_opportunity',true));$cid=absint(get_post_meta($p->ID,'_nfinite_app_creator',true));echo '<p><strong>Opportunity:</strong> '.($oid?'<a href="'.esc_url(get_edit_post_link($oid)).'">'.esc_html(get_the_title($oid)).'</a>':'—').'</p><p><strong>Creator:</strong> '.($cid?'<a href="'.esc_url(get_edit_post_link($cid)).'">'.esc_html(get_the_title($cid)).'</a>':'—').'</p><p><strong>Pitch</strong><br>'.esc_html(get_post_meta($p->ID,'_nfinite_app_pitch',true)).'</p>';self::field('_nfinite_app_deliverable_url','Deliverable / proof URL','url',$p->ID);$s=get_post_meta($p->ID,'_nfinite_app_status',true)?:'applied';echo '<p><strong>Deal status</strong><br><select name="_nfinite_app_status">';foreach(array('applied','invited','accepted','declined','in_progress','submitted','approved','cancelled') as $x)echo '<option value="'.esc_attr($x).'" '.selected($s,$x,false).'>'.esc_html(ucwords(str_replace('_',' ',$x))).'</option>';echo '</select></p>';if(get_post_meta($p->ID,'_nfinite_app_earning_recorded',true))echo '<p><strong>Creator Earnings:</strong> finalized</p>';}
	public static function save_application($id){if(!isset($_POST['nfinite_brand_app_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nfinite_brand_app_nonce'])),'nfinite_brand_app_save')||!current_user_can('edit_post',$id))return;$old=get_post_meta($id,'_nfinite_app_status',true);if(isset($_POST['_nfinite_app_deliverable_url']))update_post_meta($id,'_nfinite_app_deliverable_url',esc_url_raw(wp_unslash($_POST['_nfinite_app_deliverable_url'])));if(isset($_POST['_nfinite_app_status'])){$new=sanitize_key(wp_unslash($_POST['_nfinite_app_status']));update_post_meta($id,'_nfinite_app_status',$new);if('approved'===$new&&'approved'!==$old)self::record_earning($id);}}
	private static function creator_for_user($uid){$ids=get_posts(array('post_type'=>'nfinite_creator','post_status'=>array('publish','draft','pending'),'author'=>absint($uid),'numberposts'=>1,'fields'=>'ids'));return $ids?absint($ids[0]):0;}
	public static function login_required(){wp_safe_redirect(wp_login_url(wp_get_referer()?:home_url('/')));exit;}
	public static function apply(){if(!is_user_logged_in())self::login_required();$oid=isset($_POST['opportunity_id'])?absint($_POST['opportunity_id']):0;if(!$oid||self::OPPORTUNITY!==get_post_type($oid)||!isset($_POST['_wpnonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['_wpnonce'])),'nfinite_apply_'.$oid))wp_die('Invalid opportunity request.');$creator=self::creator_for_user(get_current_user_id());if(!$creator)wp_die('A Creator profile is required to apply.');$existing=get_posts(array('post_type'=>self::APPLICATION,'post_status'=>'any','numberposts'=>1,'meta_query'=>array(array('key'=>'_nfinite_app_opportunity','value'=>$oid),array('key'=>'_nfinite_app_creator','value'=>$creator)),'fields'=>'ids'));if(!$existing){$id=wp_insert_post(array('post_type'=>self::APPLICATION,'post_status'=>'publish','post_title'=>get_the_title($creator).' — '.get_the_title($oid)));if($id&&!is_wp_error($id)){update_post_meta($id,'_nfinite_app_opportunity',$oid);update_post_meta($id,'_nfinite_app_creator',$creator);update_post_meta($id,'_nfinite_app_user',get_current_user_id());update_post_meta($id,'_nfinite_app_pitch',sanitize_textarea_field(wp_unslash($_POST['pitch']??'')));update_post_meta($id,'_nfinite_app_status','applied');}}$url=wp_get_referer()?:get_permalink($oid);wp_safe_redirect(add_query_arg('nfinite_applied','1',$url));exit;}
	public static function shortcode($atts){$a=shortcode_atts(array('limit'=>12),$atts);$q=get_posts(array('post_type'=>self::OPPORTUNITY,'post_status'=>'publish','numberposts'=>min(50,max(1,absint($a['limit']))),'meta_key'=>'_nfinite_opp_status','meta_value'=>'open'));ob_start();echo '<div class="nfinite-opportunities">';if(isset($_GET['nfinite_applied']))echo '<p class="nfinite-notice">Application submitted.</p>';if(!$q)echo '<p>No creator opportunities are open right now.</p>';foreach($q as $o){$brand=get_post_meta($o->ID,'_nfinite_opp_brand',true);$pay=(float)get_post_meta($o->ID,'_nfinite_opp_compensation',true);$deadline=get_post_meta($o->ID,'_nfinite_opp_deadline',true);$del=get_post_meta($o->ID,'_nfinite_opp_deliverables',true);echo '<article class="nfinite-opportunity-card"><h3>'.esc_html($o->post_title).'</h3><p><strong>'.esc_html($brand).'</strong>';if($pay>0)echo ' · $'.esc_html(number_format($pay,2));if($deadline)echo ' · Apply by '.esc_html($deadline);echo '</p><div>'.wp_kses_post(wpautop($o->post_content)).'</div>';if($del)echo '<p><strong>Deliverables:</strong> '.esc_html($del).'</p>';if(is_user_logged_in()){echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="nfinite_apply_opportunity"><input type="hidden" name="opportunity_id" value="'.absint($o->ID).'">'.wp_nonce_field('nfinite_apply_'.$o->ID,'_wpnonce',true,false).'<textarea name="pitch" rows="3" placeholder="Tell the brand why you are a fit"></textarea><br><button type="submit">Apply</button></form>';}else echo '<p><a href="'.esc_url(wp_login_url(get_permalink($o))).'">Sign in to apply</a></p>';echo '</article>';}echo '</div>';return ob_get_clean();}
	private static function record_earning($app_id){if(!class_exists('Nfinite_Creators_Payments'))return;$oid=absint(get_post_meta($app_id,'_nfinite_app_opportunity',true));$creator=absint(get_post_meta($app_id,'_nfinite_app_creator',true));$amount=(int)round(((float)get_post_meta($oid,'_nfinite_opp_compensation',true))*100);if(!$creator||$amount<1||get_post_meta($app_id,'_nfinite_app_earning_recorded',true))return;Nfinite_Creators_Payments::record_earning(array('entry_key'=>'brand_deal:application:'.$app_id,'creator_id'=>$creator,'source_type'=>'sponsorship','source_id'=>(string)$oid,'source_label'=>get_the_title($oid),'earning_kind'=>'brand_deal','accounting_period'=>gmdate('Y-m'),'eligible_amount'=>$amount,'creator_amount'=>$amount,'status'=>'finalized','earning_status'=>'finalized','is_provisional'=>0,'finalized_at'=>current_time('mysql',true)));update_post_meta($app_id,'_nfinite_app_earning_recorded',current_time('mysql',true));}
	public static function opp_columns($c){$c['nfinite_brand']='Brand';$c['nfinite_pay']='Compensation';$c['nfinite_apps']='Applications';return $c;}
	public static function opp_column($col,$id){if('nfinite_brand'===$col)echo esc_html(get_post_meta($id,'_nfinite_opp_brand',true));elseif('nfinite_pay'===$col)echo '$'.esc_html(number_format((float)get_post_meta($id,'_nfinite_opp_compensation',true),2));elseif('nfinite_apps'===$col){$ids=get_posts(array('post_type'=>self::APPLICATION,'post_status'=>'any','numberposts'=>-1,'meta_key'=>'_nfinite_app_opportunity','meta_value'=>$id,'fields'=>'ids'));echo number_format(count($ids));}}
}
