<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class Nfinite_Creators_Analytics_Hub {
 public static function init(){ add_action('admin_menu',array(__CLASS__,'menu')); }
 public static function menu(){ add_menu_page('PairOfDice Analytics','Analytics Hub','manage_options','nfinite-analytics',array(__CLASS__,'page'),'dashicons-chart-area',25); }
 private static function duration($ms){ $s=(int)round($ms/1000); $h=floor($s/3600); $m=floor(($s%3600)/60); return $h ? $h.'h '.$m.'m' : $m.'m '.($s%60).'s'; }
 private static function money($n){ return '$'.number_format((float)$n,2); }
 public static function page(){
  if(!current_user_can('manage_options')) return; global $wpdb;
  $days=isset($_GET['range'])?max(1,min(365,absint($_GET['range']))):30; $start=gmdate('Y-m-d H:i:s',time()-$days*DAY_IN_SECONDS);
  $a=Nfinite_Creators_Analytics::table_name(); $e=Nfinite_Creators_Engagement::table_name();
  $site=$wpdb->get_row($wpdb->prepare("SELECT COUNT(CASE WHEN event_type='page_view' THEN 1 END) pageviews,COUNT(DISTINCT CASE WHEN event_type='page_view' THEN visitor_hash END) visitors,COUNT(DISTINCT CASE WHEN event_type='page_view' THEN session_hash END) sessions,COALESCE(SUM(CASE WHEN event_type='site_engagement' THEN engagement_ms ELSE 0 END),0) engagement_ms FROM {$a} WHERE creator_id=0 AND occurred_at >= %s",$start),ARRAY_A);
  $audio=$wpdb->get_row($wpdb->prepare("SELECT COUNT(*) raw_plays,SUM(qualified=1) qualified_streams,COUNT(DISTINCT CASE WHEN qualified=1 THEN visitor_hash END) listeners,COALESCE(SUM(listened_ms),0) listening_ms,AVG(CASE WHEN duration_ms>0 THEN completion_pct END) completion,SUM(skipped=1) skips FROM {$e} WHERE started_at >= %s",$start),ARRAY_A);
  $sources=$wpdb->get_results($wpdb->prepare("SELECT source,COUNT(*) views FROM {$a} WHERE creator_id=0 AND event_type='page_view' AND occurred_at >= %s GROUP BY source ORDER BY views DESC LIMIT 8",$start),ARRAY_A);
  $pages=$wpdb->get_results($wpdb->prepare("SELECT page_path,COUNT(*) views,COUNT(DISTINCT visitor_hash) visitors FROM {$a} WHERE creator_id=0 AND event_type='page_view' AND occurred_at >= %s GROUP BY page_path ORDER BY views DESC LIMIT 10",$start),ARRAY_A);
  $surfaces=$wpdb->get_results($wpdb->prepare("SELECT surface,COUNT(*) raw_plays,SUM(qualified=1) qualified_streams,COALESCE(SUM(listened_ms),0) listening_ms FROM {$e} WHERE started_at >= %s GROUP BY surface ORDER BY qualified_streams DESC,raw_plays DESC LIMIT 10",$start),ARRAY_A);
  $tracks=$wpdb->get_results($wpdb->prepare("SELECT object_id,MAX(metadata) metadata,COUNT(*) raw_plays,SUM(qualified=1) qualified_streams,COUNT(DISTINCT CASE WHEN qualified=1 THEN visitor_hash END) listeners,AVG(CASE WHEN duration_ms>0 THEN completion_pct END) completion FROM {$e} WHERE started_at >= %s GROUP BY object_id ORDER BY qualified_streams DESC,raw_plays DESC LIMIT 10",$start),ARRAY_A);
  $new_creators=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->posts} WHERE post_type='nfinite_creator' AND post_status='publish' AND post_date_gmt >= %s",$start));
  $revenue=0;$purchases=0; $rows=$wpdb->get_results($wpdb->prepare("SELECT metadata FROM {$a} WHERE event_type='purchase' AND occurred_at >= %s",$start),ARRAY_A); foreach($rows as $r){$m=json_decode($r['metadata'],true); if(is_array($m)){$revenue+=(float)($m['revenue']??0);$purchases++;}}
  $views=(int)($site['pageviews']??0);$visitors=(int)($site['visitors']??0);$sessions=(int)($site['sessions']??0);$eng=(int)($site['engagement_ms']??0);$qs=(int)($audio['qualified_streams']??0);$raw=(int)($audio['raw_plays']??0);$skip=(int)($audio['skips']??0);
  ?><div class="wrap nfinite-hub"><style>
  .nfinite-hub{max-width:1440px}.nfinite-hub h1{font-size:30px;margin:24px 0 4px}.nfinite-hub .sub{color:#646970;margin:0 0 20px}.nf-ranges{display:flex;gap:6px;margin:14px 0 22px}.nf-ranges a{padding:7px 12px;border:1px solid #c3c4c7;border-radius:20px;text-decoration:none;background:#fff}.nf-ranges a.on{background:#1d2327;color:#fff;border-color:#1d2327}.nf-cards{display:grid;grid-template-columns:repeat(6,minmax(150px,1fr));gap:12px}.nf-card,.nf-panel{background:#fff;border:1px solid #dcdcde;border-radius:10px;padding:18px;box-shadow:0 1px 2px rgba(0,0,0,.03)}.nf-card span{display:block;color:#646970;font-size:12px;text-transform:uppercase;letter-spacing:.04em}.nf-card strong{display:block;font-size:26px;margin-top:8px}.nf-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.nf-panel h2{margin-top:0}.nf-table{width:100%;border-collapse:collapse}.nf-table th,.nf-table td{text-align:left;padding:10px 8px;border-bottom:1px solid #eee}.nf-table th{font-size:11px;text-transform:uppercase;color:#646970}.nf-note{margin-top:16px;padding:14px 18px;background:#f6f7f7;border-left:4px solid #2271b1}@media(max-width:1100px){.nf-cards{grid-template-columns:repeat(3,1fr)}}@media(max-width:782px){.nf-cards,.nf-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.nf-cards,.nf-grid{grid-template-columns:1fr}}
  </style><h1>PairOfDice Analytics Hub</h1><p class="sub">First-party operating dashboard for audience, listening, creators and commerce. Use GA4 alongside this hub for deeper acquisition and advertising attribution.</p><div class="nf-ranges"><?php foreach(array(7=>'7D',30=>'30D',90=>'90D',365=>'12M') as $d=>$l):?><a class="<?php echo $days===$d?'on':'';?>" href="<?php echo esc_url(add_query_arg('range',$d,admin_url('admin.php?page=nfinite-analytics')));?>"><?php echo esc_html($l);?></a><?php endforeach;?></div>
  <div class="nf-cards">
  <?php $cards=array('Visitors'=>number_format_i18n($visitors),'Sessions'=>number_format_i18n($sessions),'Pageviews'=>number_format_i18n($views),'Engaged Time'=>self::duration($eng),'Qualified Streams'=>number_format_i18n($qs),'Listening Time'=>self::duration((int)($audio['listening_ms']??0)),'Unique Listeners'=>number_format_i18n((int)($audio['listeners']??0)),'Avg. Completion'=>round((float)($audio['completion']??0),1).'%','Skip Rate'=>$raw?round($skip/$raw*100,1).'%':'0%','New Creators'=>number_format_i18n($new_creators),'Creator Purchases'=>number_format_i18n($purchases),'Creator Revenue'=>self::money($revenue)); foreach($cards as $k=>$v):?><div class="nf-card"><span><?php echo esc_html($k);?></span><strong><?php echo esc_html($v);?></strong></div><?php endforeach;?></div>
  <div class="nf-grid"><section class="nf-panel"><h2>Top pages</h2><table class="nf-table"><tr><th>Page</th><th>Views</th><th>Visitors</th></tr><?php foreach($pages as $r):?><tr><td><?php echo esc_html($r['page_path']?:'/');?></td><td><?php echo number_format_i18n($r['views']);?></td><td><?php echo number_format_i18n($r['visitors']);?></td></tr><?php endforeach;?></table></section>
  <section class="nf-panel"><h2>Traffic sources</h2><table class="nf-table"><tr><th>Source</th><th>Pageviews</th></tr><?php foreach($sources as $r):?><tr><td><?php echo esc_html(ucwords(str_replace('_',' ',$r['source'])));?></td><td><?php echo number_format_i18n($r['views']);?></td></tr><?php endforeach;?></table></section></div>
  <div class="nf-grid"><section class="nf-panel"><h2>Listening surfaces</h2><table class="nf-table"><tr><th>Surface</th><th>Raw</th><th>Qualified</th><th>Time</th></tr><?php foreach($surfaces as $r):?><tr><td><?php echo esc_html(ucwords(str_replace('_',' ',$r['surface'])));?></td><td><?php echo number_format_i18n($r['raw_plays']);?></td><td><?php echo number_format_i18n($r['qualified_streams']);?></td><td><?php echo esc_html(self::duration((int)$r['listening_ms']));?></td></tr><?php endforeach;?></table></section>
  <section class="nf-panel"><h2>Top tracks</h2><table class="nf-table"><tr><th>Track</th><th>Qualified</th><th>Listeners</th><th>Completion</th></tr><?php foreach($tracks as $r):$m=json_decode((string)$r['metadata'],true);$title=is_array($m)&&!empty($m['title'])?$m['title']:(get_post_status($r['object_id'])?get_the_title($r['object_id']):'Track #'.$r['object_id']);?><tr><td><?php echo esc_html($title);?></td><td><?php echo number_format_i18n($r['qualified_streams']);?></td><td><?php echo number_format_i18n($r['listeners']);?></td><td><?php echo esc_html(round((float)$r['completion'],1));?>%</td></tr><?php endforeach;?></table></section></div>
  <div class="nf-note"><strong>Data boundary:</strong> PairOfDice first-party analytics starts collecting site-wide page activity with this version. Historical site-wide traffic from before installation is not backfilled. Existing creator, audio and earnings history remains intact.</div></div><?php
 }
}
